services:
  web:
    image: nginx:1.23.3
    container_name: php-nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html
      - ./docker/ssl/certs:/etc/ssl/certs
      - ./docker/ssl/private:/etc/ssl/private
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php

  php:
    build: .
    container_name: php-fpm
    volumes:
      - ./:/var/www/html
      - ./docker/xdebug/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/xdebug/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    links:
      - db

  db:
    image: mysql:8.0.31-debian
    container_name: php-mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
